apiVersion: v1
kind: Service
metadata:
  name: codebase
  namespace: codebase
  labels:
    app: codebase
spec:
  type: ClusterIP
  selector:
    app: codebase
  ports:
    - name: http
      port: 80
      targetPort: http   # 81 (Caddy inside the pod)
      protocol: TCP
    - name: nextjs
      port: 3000
      targetPort: nextjs # 3000 (direct, for in-cluster debugging only)
      protocol: TCP
